# MongoDB Configuration
quarkus.mongodb.connection-string=${QUARKUS_MONGODB_CONNECTION_STRING}
mp.messaging.connector.smallrye-kafka.bootstrap.servers=${QUARKUS_KAFKA_BOOTSTRAP_SERVERS}
quarkus.mongodb.database=collections

# Kafka Bootstrap Servers
kafka.bootstrap.servers=${QUARKUS_KAFKA_BOOTSTRAP_SERVERS}

mp.messaging.incoming.sync-addresses.connector=smallrye-kafka
mp.messaging.incoming.sync-addresses.topic=sync-addresses
mp.messaging.incoming.sync-addresses.group.id=collections-service
mp.messaging.incoming.sync-addresses.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.sync-addresses.auto.offset.reset=earliest

mp.messaging.incoming.sync-collectors.connector=smallrye-kafka
mp.messaging.incoming.sync-collectors.topic=-collector-sync
mp.messaging.incoming.sync-collectors.group.id=collections-service
mp.messaging.incoming.sync-collectors.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.sync-collectors.auto.offset.reset=earliest

# Reactive Messaging - Outgoing Channels (Producers)
mp.messaging.outgoing.collection-events-out.connector=smallrye-kafka
mp.messaging.outgoing.collection-events-out.topic=collection-events
mp.messaging.outgoing.collection-events-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Logging
quarkus.log.level=INFO
quarkus.log.category."org.example".level=DEBUG

# REST
quarkus.rest.path=/api

